version: "3.8"
services:

  # data base
  postgres:
    image: postgres:15
    container_name: tingeso-postgres
    environment:
      POSTGRES_DB: tingeso_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: tingeso-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "9090:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - backend-network

  # 3  backend
  tingeso-backend-1:
    image: lucianoxhdx/tingeso-backend:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tingeso_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/spring-boot-realm-tingeso
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/spring-boot-realm-tingeso/protocol/openid-connect/certs
    depends_on:
      - postgres
      - keycloak
    networks:
      - backend-network

  tingeso-backend-2:
    image: lucianoxhdx/tingeso-backend:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tingeso_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/spring-boot-realm-tingeso
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/spring-boot-realm-tingeso/protocol/openid-connect/certs
    depends_on:
      - postgres
      - keycloak
    networks:
      - backend-network

  tingeso-backend-3:
    image: lucianoxhdx/tingeso-backend:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tingeso_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/spring-boot-realm-tingeso
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/spring-boot-realm-tingeso/protocol/openid-connect/certs
    depends_on:
      - postgres
      - keycloak
    networks:
      - backend-network

  # Nginx for backend
  nginx-backend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - tingeso-backend-1
      - tingeso-backend-2
      - tingeso-backend-3
    networks:
      - backend-network
      - frontend-network

  # 3  frontend
  tingeso-frontend-1:
    image: lucianoxhdx/tingeso-frontend:latest
    networks:
      - frontend-network

  tingeso-frontend-2:
    image: lucianoxhdx/tingeso-frontend:latest
    networks:
      - frontend-network

  tingeso-frontend-3:
    image: lucianoxhdx/tingeso-frontend:latest
    networks:
      - frontend-network

  # Nginx for front
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:8070"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - tingeso-frontend-1
      - tingeso-frontend-2
      - tingeso-frontend-3
    networks:
      - frontend-network

networks:
  frontend-network:
  backend-network:

volumes:
  postgres-data:
  keycloak-data: